### ISSUE TITLE
Not All Scenarios Are Written To Test Report

### ISSUE THREAD

**Issue by grantsheppard** [hauner/grails-cucumber#33]
In our Grails app we have two Cucumber features, each with one scenario. 

When running these tests (grails test-app) the report generated in target/test-reports/TEST-functional-cucumber-.xml only contain one of the features and scenarios. However all of the tests are running so it only seems to be a problem with the reporting.

I'm using the following versions: -

Grails 2.3.0
Cucumber Plugin 0.9.0

**Comment by hauner** [comment]
tidy up.
