### ISSUE TITLE
failed testing grails cucumber

### ISSUE THREAD

**Issue by calime** [hauner/grails-cucumber#35]
Hello,

I download the code at : https://github.com/hauner/grails-cucumber
And when I test this code by executing : grails test-app functional:cucumber
I get this error : 
 Error Fatal error running tests: ServletContext must not be null

I'm using grails v2.3.7. I really don't understand why this error happens. I have searched on the web differents possibilities but all I found lead to nothing.

Regards

**Comment by hauner** [comment]
tidy up.
