### ISSUE TITLE
ConfigCucumber.groovy is hardcoded

### ISSUE THREAD

**Issue by Luxor** [hauner/grails-cucumber#43]
Ability to change name of configuration file is really wanted when grails application is splited into inline plugins (each plugin has CucumberConfig file). In this case CucumberConfig will be compiled multiple times and this leads to compilation error: the same class already compiled or so.

This can be easly fixed by adding abililty to set any name for "CucumberConfig.groovy"

**Comment by hauner** [comment]
I'm able to reproduce the issue.

I think I will read the cucumber configuration from grails' standard configuration file. This way we can simply drop `CucumberConfig.groovy`.

**Comment by Luxor** [comment]
Sounds good. Thanks

**Comment by hauner** [comment]
released 1.2.0, you can now drop `CucumberConfig.groovy` and copy its content to `BuildConfig.groovy`.

**Comment by Luxor** [comment]
Thanks a lot!!!
