### ISSUE TITLE
is the hook "integration" still supported in plugin 1.2 grails 2.3 ?

### ISSUE THREAD

**Issue by djocal** [hauner/grails-cucumber#44]
hello,
the doc says it's "deprecated", do you mean it does not work any more or it's not recommended any more ?
given env.groovy 

``` groovy
import static grails.plugin.cucumber.Hooks.hooks
hooks {
    integration ("@integration")
}
```

and i put the tag @integration above a "scenario"
when the step calls a gorm method
then it crashes with "IllegalStateException: Method on class [my domain class here] was used outside of a Grails application"

Thank you for the precisions.
(i'm interested in having access to gorm and spring (appCtx) to port existing integration tests to cucumber)

**Comment by hauner** [comment]
It is not recommended anymore. It should still work but in non-forked mode only. It will not work in forked mode because the tests then run in a second jvm and not "inside" the grails app. That may cause the exception you see.

**Comment by djocal** [comment]
thank you for your answer. i got this problem with grails 2.3.x in non forked mode, so the problem may affect this specific version of grails. I let you know if i got the same problem with 2.4 and more.

Cheers.
